#%RAML 1.0 NamedExample

value: 
  -
    firstName: john
    lastName: doe
    address: New York
    postal: '568240'
    country: USA
    miles: 4
    type: 'personal'

  - 
    firstName: jack
    lastName: hammer
    address: California
    postal: '600078'
    country: USA
    miles: 6
    type: 'business'