#%RAML 1.0 NamedExample

value: 
  -
    ID?: 1
    firstName: john
    lastName: doe
    address: New York
    postal: '568240'
    country: USA
    miles: 4
    creationDate: 2021-05-31T10:41:41.090Z
    type: 'personal'

  - 
    ID?: 2
    firstName: jack
    lastName: hammer
    address: California
    postal: '600078'
    country: USA
    miles: 6
    creationDate: 2021-11-09T10:41:41.090Z
    type: 'business'